name: Build Greene Genie Executable

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller Pillow
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name=GreeneGenie --add-data="GK Logo.png;." wave_greeter.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: GreeneGenie-Windows
        path: dist/GreeneGenie.exe
